"""Debit and Credit column changed to float

Revision ID: 1a7e2ba90c59
Revises: ece2e3f6e624
Create Date: 2025-06-22 21:14:13.458199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a7e2ba90c59'
down_revision: Union[str, Sequence[str], None] = 'ece2e3f6e624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'credit',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'debit',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'debit',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'credit',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
