"""title and type column non-nullable

Revision ID: 2ad31cbe9860
Revises: 59a11fe883f8
Create Date: 2025-06-24 00:32:53.161741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ad31cbe9860'
down_revision: Union[str, Sequence[str], None] = '59a11fe883f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'Not added.'::character varying"))
    op.alter_column('transactions', 'transaction_type',
               existing_type=postgresql.ENUM('income', 'expense', name='transaction_type_enum'),
               nullable=False,
               existing_server_default=sa.text("'expense'::transaction_type_enum"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'transaction_type',
               existing_type=postgresql.ENUM('income', 'expense', name='transaction_type_enum'),
               nullable=True,
               existing_server_default=sa.text("'expense'::transaction_type_enum"))
    op.alter_column('transactions', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'Not added.'::character varying"))
    # ### end Alembic commands ###
