"""title and type column added

Revision ID: 59a11fe883f8
Revises: 1a7e2ba90c59
Create Date: 2025-06-24 00:27:52.941769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '59a11fe883f8'
down_revision: Union[str, Sequence[str], None] = '1a7e2ba90c59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
transaction_type_enum = postgresql.ENUM('income', 'expense', name='transaction_type_enum')

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    transaction_type_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('transactions', sa.Column('title', sa.String(), server_default='Not added.', nullable=True))
    op.add_column('transactions', sa.Column('transaction_type', sa.Enum('INCOME', 'EXPENSE', name='transaction_type_enum'), server_default='expense', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'transaction_type')
    op.drop_column('transactions', 'title')
    transaction_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
