name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Or your deployment branch

jobs:
  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Build and Push Docker Image to Artifact Registry
        run: |
          docker build -t asia-south1-docker.pkg.dev/expensetracker-467016/expense-repo/fastapi-app:$GITHUB_SHA .
          docker push asia-south1-docker.pkg.dev/expensetracker-467016/expense-repo/fastapi-app:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fastapi-app \
            --image=asia-south1-docker.pkg.dev/expensetracker-467016/expense-repo/fastapi-app:$GITHUB_SHA \
            --region=asia-south1 \
            --platform=managed \
            --allow-unauthenticated \
            --port=8000
